spring:
  application:
    name: rabbitmq
  rabbitmq: #rabbitmq配置文件
    host: 192.168.88.129
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true #发布确认 生产者发送消息到Exchange时生效
    publisher-returns: true #发布返回 Exchange发送消息到Queue时生效
    listener:
      simple:
        acknowledge-mode: manual #消息确认接收 none(不确认),manual(手动确认),auto(自动确认)。Queue发送消息到消费者时生效


